# Generated by Django 5.0.1 on 2024-01-18 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProjetoH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_fila', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 8, 0, 17, 461233)),
        ),
    ]
