# Generated by Django 3.2.23 on 2024-01-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProjetoH', '0002_peoplecount_alter_vendas_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='Vendedor',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='nome_produto',
        ),
        migrations.RemoveField(
            model_name='peoplecount',
            name='situacao_fila',
        ),
        migrations.AddField(
            model_name='peoplecount',
            name='situacao_fila_banco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Vendas',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
