# Generated by Django 3.2.23 on 2024-01-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProjetoH', '0003_auto_20240118_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoEnquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bemVida', models.IntegerField(default=0)),
                ('grill', models.IntegerField(default=0)),
                ('modaCasa', models.IntegerField(default=0)),
                ('receitaChefe', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
